### PR TITLE
Rewrite code for Basic Authentication

### PR DESCRIPTION
**Pull request by accc703**
Decode the Authorization header, and compare the user records in Get-RestUserAuth.ps1

### CODE REVIEW

**Comment by jpsider** [comment]
Looks like the build failed due to 'PSAvoidTrailingWhitespace'
Not sure which line, but one of them has some extra whitepsace.

**Comment by jpsider** [comment]
Line 9, 43

**Comment by accc703** [comment]
> Line 9, 43

Just removed the whitespace at the line mentioned

**Comment by jpsider** [comment]
https://ci.appveyor.com/project/JustinSider/restps/builds/32584653

hmm, still missing something. I'm on my phone, so I can't take a look now. you can run scriptanalyzer locally on that file to get the exact lines.

**Comment by accc703** [comment]
> https://ci.appveyor.com/project/JustinSider/restps/builds/32584653

Thank you. I am totally new on github

**Comment by jpsider** [comment]
Github can be tricky! - I'm happy having folks conrtibute!
Instead of doing a foreach loop. What about doing a where, that way you can limit it to one check.
`
# Untested

$RequestUserName,$RequestPass = $DecodedAuthString -split (":")
$AllowedUser = $RestUserAuth | Where-Object {$_.UserName -eq "$RequestUserName"}

If(($AllowedUser | Measure-Object).Count -eq 1) {
    # Perform the check
} else {
    # Incorrect number of Matches
}
`

**Comment by accc703** [comment]
> Measure-Object

If using WHERE, would the following code logically correct, by checking the username and password at the same line?

$AllowedUser = $RestUserAuth | Where-Object {($_.UserName -eq "$RequestUserName") -And ($_.SystemAuthString -eq "$RequestPass)}
If(($AllowedUser | Measure-Object).Count -eq 1) {
$script:VerifyStatus = $true
} else {
$script:VerifyStatus = $false
}`

**Comment by jpsider** [comment]
In theory, yes!  - But it would need to functionally be tested.

**Comment by accc703** [comment]
Let me try to program and test, and create pull again.

**Pull request closed without merging**
