### PR TITLE
Support Get Process by PID

### PR DESCRIPTION
**Pull request by robinmalik**
Support Get Process by PID. We required this ability at work, and I thought it'd be a useful option to have in the module.

### CODE REVIEW

**Comment by robinmalik** [comment]
Yes:

```
ERROR: Cannot bind argument to parameter 'CoverallsApiToken' because it is an empty string.
At C:\projects\restps\module.build.ps1:33 char:80
+ ... terResults $TestResults -CoverallsApiToken $ENV:Coveralls_Key -Branch ...
+                                                ~~~~~~~~~~~~~~~~~~
At C:\projects\restps\module.build.ps1:31 char:1
+ Task Publish_Unit_Tests_Coverage {
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:\projects\restps\module.build.ps1:16 char:1
+ Task Pester Build, ImportModule, UnitTests, FullTests, Publish_Unit_T ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:\projects\restps\module.build.ps1:14 char:1
+ Task Default Build, Pester, UpdateSource, Publish
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Build FAILED. 11 tasks, 1 errors, 0 warnings 00:02:13.1392551
Cannot bind argument to parameter 'CoverallsApiToken' because it is an empty string.
```
I don't understand it though (it doesn't appear related to any change I made). Are you able to elaborate on this?

**Comment by jpsider** [comment]
I can take a look at it a bit later today, I'm about to hop on a plane for a couple hours.

**Comment by robinmalik** [comment]
@jpsider No rush at all :)

**Comment by jpsider** [comment]
Build worked for me, I will deploy it to the Gallery in a little bit.

**Comment by jpsider** [comment]
Package published - RestPS 7.0.40

**Comment by robinmalik** [comment]
That's great, thanks (though in retrospect I wonder if it should have been "id" rather than "pid" - oversight in bolting this functionality on for a specific job at work). 

For future reference, is there anything that can be done to avoid getting AppVeyor failures and you having to manually run tests? It seems like a pain for you, for such minor tweaks to the module.

**Comment by jpsider** [comment]
It's all good. I didn't actually do anything. The error you saw was caused by a environmental variable I think.

**Pull request merged**
