### PR TITLE
Add a new CA verification function

### PR DESCRIPTION
**Pull request by matsmcp**
Adds a new function for a more flexible Certificate/CA verification.  By setting $checkcertificate=$true in Get-RestCAList.ps1 the test-certificate cmdlet will be used to verify that the calling client cert is trusted by the server.

Intended to be used as a verification type.

Also decouples the server Certificate from the verification of the client cert and therefore adds support for PKI designs with more than one CA level.

Also uses Invoke-Expression (get-content -Path ...) instead of dot sourcing to speed up loading of subscripts ( dot sourcing seems to be very slow on PS 5.1).

I see further enhancements (for example dot sourcing on core (where it seems fast) and Invoke-Expression on 5.1. There are dot sourcing in more files that should be fixed too but I'll make an initial commit before I leave on vacation

### CODE REVIEW

**Comment by jpsider** [comment]
I'm on vacation for the next couple weeks. I'll review this once I'm back home.

**Comment by jpsider** [comment]
do you think these files are in the right location or do you think they should be moved to /bin ?

**Comment by matsmcp** [comment]
Oops, should be in /bin in my eyes.
Im hopefully better at writing code than using Github ....

**Comment by jpsider** [comment]
I moved the files. But looks like we have some issues with the build.
image
image

the last one we should be able to get around - the others we will need to correct.
You can do an updated pull, make the changes then submit a new Pull request.

Add this to the 2nd file after [CmdletBinding()]
[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidUsingInvokeExpression", '')]

**Comment by matsmcp** [comment]
Back at the office. 

I have fixed the two errors in Get-RestCAList.ps1
I also fixed the whitespaces in Invoke-VerifyCA.ps1
I have tried (and failed) to fix the InvokeExpression error. 

The current code is in https://github.com/matsmcp/RestPS.
I haven't created a pull request since there is one error remaning but I have no idea how to fix it
Also needs more testing

**Comment by jpsider** [comment]
Sorry, just seeing this!
To resolve the Invoke-Expression just ...
Add this to the 2nd file after [CmdletBinding()]
[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidUsingInvokeExpression", '')]

go ahead and submit a new PR

**Comment by jpsider** [comment]
Just make sure you do a fresh pull before you submit the PR to get your latest changes with the new check you added.

**Comment by jpsider** [comment]
Just Kidding! I was able to get your changes in the newest release for both PR's - https://www.powershellgallery.com/packages/RestPS/7.0.58

**Pull request merged**
